- hosts: all
  remote_user: edureka
  gather_facts: no

  tasks:        
    - name: Deploy docker artifacyts over Kuernetes
      command: docker run -d --name abctech-docker-container -p 1585:8080 abctech-docker-image
      register: deploy

